VSPHERE_DATACENTER: QC-DC
VSPHERE_DATASTORE: esxi-00-local-ds-01
VSPHERE_NETWORK: internal-svcs-vlan-253
VSPHERE_FOLDER: k8s_vms
VSPHERE_TEMPLATE: base-os-latest
VSPHERE_HAPROXY_TEMPLATE: ha-proxy-latest-ova
VSPHERE_DISK_GIB: 50
VSPHERE_NUM_CPUS: 2
VSPHERE_MEM_MIB: 4096
VSPHERE_SSH_AUTHORIZED_KEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCzZ46aJr0VtvnbqX53grrivXVrn9p13mQA8T/8XRNE3UjipBJArYOSQvlLdofr10LKq/hLFyxzgLJJigdzqER3v3uw7JPLf3aUlMBo2YZfdAtE1JfMM2qpUBcWY5z5xIpLjCCBnOFWKZ2nxA+2bsqExHix7myMM8Av6GFWUzbzebS5ba9dATgc1W/ddZ26zR6saywdcDqx/KZYQWCaXsknukR5zYyq9xon1zquCRuhqaerE3sWQcEnEmR06E0jst/DRZ4x4lfbXNu8Rvs7uaZInE8AhhMZOk7lYZgAbNsVC+vdUvZ+Gxjly4f1eeh1B8ap/hSHAK6aL9PM9eWqEGhCkcZMBTHp/UhWKYoCvOdWOgTU6DaeYWnkYIwcWu4Ih5MBvKdxmfKR6aGLeDuPf2yN5hvyd63GS/X17q18c9uSFrDKEzalNN3dkY2YeWZ03kP9l/c1075+OX98GpQCvgirA93FfzgV3KHOlD8ueM+MUzFA8u2IEA4XLEBif6B4mQ0= tstacey@starscream
SERVICE_CIDR: 100.64.0.0/13
CLUSTER_CIDR: 100.96.0.0/11