resources:
- name: base-os-ova
  type: s3
  source:
    bucket: releases
    versioned_file: base-os-latest.ova
    access_key_id: ACCESS-KEY
    secret_access_key: SECRET
- name: ha-proxy-ova
  type: s3
  source:
    bucket: ((s3_bucket))
    versioned_file: ha-proxy-latest.ova
    access_key_id: ((s3_access_key))
    secret_access_key: ((s3_secret))
    endpoint: ((s3_endpoint))
- name: tkg-ci
  type: git
  source:
    uri: git@github.com:subsetsurprise/tkg-ci.git
    branch: master

jobs:
- name: upload-ova
  plan:
  - aggregate:
    - get: base-os-ova
    - get: ha-proxy-ova
    - get: govc
  - inputs:
  - name: ha-proxy-ova
  - name: base-os-ova
  - task:
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: czero/pvd-infrastructure-automation
          tag: latest
    params:
      GOVC_CA_CERT: ((vcenter_ca_cert))
      GOVC_DATACENTER: ((vcenter_datacenter))
      GOVC_DATASTORE: ((vcenter_datastore))
      GOVC_HOST: ((opsman_vm_host))
      GOVC_INSECURE: ((vcenter_insecure))
      GOVC_NETWORK: ((opsman_vm_network))
      GOVC_PASSWORD: ((vcenter_password))
      GOVC_URL: ((vcenter_host))
      GOVC_USERNAME: ((vcenter_username))
    run:
      path: tkg-ci/scripts/upload-ova.sh
  - task: upload-ha-proxy-ova
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: czero/pvd-infrastructure-automation
          tag: latest
    params:
      GOVC_CA_CERT: ((vcenter_ca_cert))
      GOVC_DATACENTER: ((vcenter_datacenter))
      GOVC_DATASTORE: ((vcenter_datastore))
      GOVC_HOST: ((opsman_vm_host))
      GOVC_INSECURE: ((vcenter_insecure))
      GOVC_NETWORK: ((opsman_vm_network))
      GOVC_PASSWORD: ((vcenter_password))
      GOVC_RESOURCE_POOL: ((opsman_resource_pool))
      GOVC_URL: ((vcenter_host))
      GOVC_USERNAME: ((vcenter_username))
      VM_FOLDER: ((vm_folder))
    run:
      path: tkg-ci/scripts/upload-ova.sh
- name: deploy-tkg
