resource_types:
- name: file-url
  type: docker-image
  source:
    repository: pivotalservices/concourse-curl-resource
    tag: latest
resources:
- name: tkg-ci
  type: git
  source:
    uri: https://github.com/subsetsurprise/tkg-ci.git
    branch: master
- name: tkg-cli
  type: file-url
  source:
    url: http://pvtl-jumpbox.qc.on-target.tech:8080/tkg
    filename: tkg
- name: ha-proxy-ova
  type: file-url
  source:
    url: http://pvtl-jumpbox.qc.on-target.tech:8080/ha-proxy-latest.ova
    filename: ha-proxy-latest.ova
- name: base-os-ova
  type: file-url
  source:
    url: http://pvtl-jumpbox.qc.on-target.tech:8080/base-os-latest.ova
    filename: base-os-latest.ova

jobs:
- name: upload-templates
  serial: true
  plan:
  - aggregate:
    - get: base-os-ova
    - get: ha-proxy-ova
    - get: tkg-ci
  - task: upload-base-os-ova
    file: tkg-ci/tasks/upload-base-os.yml
    params:
      GOVC_CA_CERT: ((vcenter_ca_cert))
      GOVC_DATACENTER: ((vcenter_datacenter))
      GOVC_DATASTORE: ((vcenter_datastore))
      GOVC_HOST: ((k8s_vm_host))
      GOVC_INSECURE: ((vcenter_insecure))
      GOVC_NETWORK: ((k8s_vm_network))
      GOVC_PASSWORD: ((vcenter_password))
      GOVC_URL: ((vcenter_host))
      GOVC_USERNAME: ((vcenter_username))
    inputs:
      - base-os-ova
  - task: upload-ha-proxy-ova
    file: tkg-ci/tasks/upload-ha-proxy.yml
    params:
      GOVC_CA_CERT: ((vcenter_ca_cert))
      GOVC_DATACENTER: ((vcenter_datacenter))
      GOVC_DATASTORE: ((vcenter_datastore))
      GOVC_HOST: ((k8s_vm_host))
      GOVC_INSECURE: ((vcenter_insecure))
      GOVC_NETWORK: ((k8s_vm_network))
      GOVC_PASSWORD: ((vcenter_password))
      GOVC_URL: ((vcenter_host))
      GOVC_USERNAME: ((vcenter_username))
    inputs:
      - ha-proxy-ova
- name: deploy-tkg
  serial: true
  plan:
  - aggregate:
    - get: tkg-ci
      passed:
      - upload-templates
    - get: tkg-cli
  - task: tkg-init
    file: tkg-ci/tasks/tkg-init.yml
    params:
      VSPHERE_SERVER: ((vcenter_host))
      VSPHERE_USERNAME: ((vcenter_username))
      VSPHERE_PASSWORD: ((vcenter_password))
    inputs:
      - tkg-cli
