---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: czero/pvd-infrastructure-automation
    tag: latest

params:
  GOVC_INSECURE:
  GOVC_CA_CERT:
  GOVC_URL:
  GOVC_USERNAME:
  GOVC_PASSWORD:
  GOVC_DATACENTER:
  GOVC_DATASTORE:
  GOVC_NETWORK:
  GOVC_HOST:
  VM_FOLDER:

inputs:
  - name: tkg-ci
run:
  path: tkg-ci/scripts/upload-ha-proxy.sh